name: WorldGuard
main: com.rustret.rg.WorldGuard
version: "1.0.0"
api: ["1.0.0"]
author: rustret
description: Plugin for protecting players area

commands:
  wand:
    usage: "/wand"
  rg:
    rg: "/rg"